### ISSUE TITLE
Show Similar Projects on the Project Details View

### ISSUE THREAD

**Issue by camelspeed** [Project-Heimdall/heimdall-uiapp#104]
- [ ] Using relevant search modeling we will have data on other projects that may fit the current project your viewing.  The goal of these suggestions is to promote reuse and collaboration.

**Comment by onetrickwolf** [comment]
@herrjosua is doing the markup I am setting up the call and logic with some dummy results

**Comment by herrjosua** [comment]
I have added the `HTML` markup and `LESS` styles to the branch #104.

**Comment by onetrickwolf** [comment]
Data with real API is in, variables dumped in HTML as reference for @herrjosua , just need new project details styling and this should be done for now.
