### ISSUE TITLE
Assist user searches by autocorrecting misspelled words

### ISSUE THREAD

**Issue by camelspeed** [Project-Heimdall/heimdall-uiapp#106]
**Acceptance Criteria**
- [ ] Misspelling common words should still return results.  For example, typing Jaba should return results for Java or Aggile should return Agile results.
- [ ] The corrections are applied behind the scenes and results returned.  The UI technically does not have an indication that corrections took place other than results were returned.  This issue is here for testing purposes.

**Comment by onetrickwolf** [comment]
Nothing to change on UI but confirming it works as expected. Testing "jaba" to return "java" results. Testing "congition" to return a set with "cognition" in it.

**Comment by farahfarahmand** [comment]
Misspelled words return results, although there were couple of observations that I discuss with Johnny and per his direction took notes of them to review later.
