### ISSUE TITLE
Refresh UI Look and Feel for Demo

### ISSUE THREAD

**Issue by camelspeed** [Project-Heimdall/heimdall-uiapp#108]
All views that change will link to this issue.  Please be atomic and detail your commits so we know what this is enhancing.

**Comment by herrjosua** [comment]
We have updated the look and feel of the `Popular` view. A few items are left to do on the `Popular` view which include updated the search input, and a few minor tweaks to styles including adding some `CSS3` animations. We might need to revisit using a single template for all the main views as the new design has a different search area. Also the filter sidebar will need to be revisited.
