### ISSUE TITLE
Search Results View

### ISSUE THREAD

**Issue by camelspeed** [Project-Heimdall/heimdall-uiapp#12]
@camelspeed commented on [Mon Jun 06 2016](https://github.com/Project-Heimdall/heimdall-webapp/issues/13)

Mockup the Search Results.  Feel free to experiment visually (e.g text vs. graphical).

---

@herrjosua commented on [Fri Jun 10 2016](https://github.com/Project-Heimdall/heimdall-webapp/issues/13#issuecomment-225190981)

### Search Results
![search results alt](https://cloud.githubusercontent.com/assets/1341786/15966836/d109c20e-2ef2-11e6-9183-35cf5d7f0e67.png)

---

@camelspeed commented on [Fri Jun 17 2016](https://github.com/Project-Heimdall/heimdall-webapp/issues/13#issuecomment-226770017)

initial layout shows promise. We need to explore what other info is most relevant so the user can make quick glances to determine if the result is relevant or interesting.

**Comment by herrjosua** [comment]
Search results view has been updated based on the mockup. Moving story to QA.

**Comment by camelspeed** [comment]
We have a very basic view but the details of the page and other features are not really defined.  This is being closed in preference for #35
