### ISSUE TITLE
Update Popular view HTML markup and LESS

### ISSUE THREAD

**Issue by herrjosua** [Project-Heimdall/heimdall-uiapp#133]
Updating the layout of `Popular` to match the mockup's produced by Ben. Also update the header section of the secondary to include a smaller search bar as per the mockups.

**Comment by camelspeed** [comment]
@herrjosua @btrayn Let's discuss what all needs to happen to the UI and when/why before creating issues.  I want the boards to be clean and the issues as well written and though through.  The intent and value needs to be clear in an issue.  The description here can be clearer and the title does not help much in understanding the what/why/how.

**Comment by camelspeed** [comment]
other issues to cover the intent of this in play. This is no longer needed.
