### ISSUE TITLE
Fix Alignment issues with live data from Github

### ISSUE THREAD

**Issue by herrjosua** [Project-Heimdall/heimdall-uiapp#25]
The alignment of cards is off, since we are now pulling data from Github for both Popular, and Browse pages.

**Comment by camelspeed** [comment]
I am still seeing alignment issues with dynamic data distorting card sizes and causing gaps in the layout.

**Comment by herrjosua** [comment]
New Card styles should resolve this issue. I will continue to test to see if I see any issues.

**Comment by camelspeed** [comment]
appears to be corrected although it was a simple manual test.  This issue will be closely monitored as we progress.
