### ISSUE TITLE
Update card markup and styles

### ISSUE THREAD

**Issue by herrjosua** [Project-Heimdall/heimdall-uiapp#28]
![screen shot 2016-07-06 at 12 52 39](https://cloud.githubusercontent.com/assets/1341786/16627145/05494abc-437a-11e6-9e2f-d3ab14792c23.png)

**Comment by camelspeed** [comment]
I know what you posted and we discussed in the product design channel but that differs from the image above.  I actually disliked the options in the channel with the README so prominent in the middle.  It looks like it is handing in mid-air and breaking the reading lines of the card. I assumed (which I should not have) that above was what is getting in.  Please make it like above BUT continue to have the horizontal separator between the description and readme/travis/package links.

**Comment by camelspeed** [comment]
That should be ok for now until we have some in depth design sessions in the coming week in person.

**Comment by herrjosua** [comment]
Ok I will refractor the readme back to the same line.

**Comment by herrjosua** [comment]
Moved the Readme link back to the same line as the other items. Moving back to Review/QA status.
