### ISSUE TITLE
Update the HTML markup to match the approved wireframe posted in the product-design channel

### ISSUE THREAD

**Issue by camelspeed** [Project-Heimdall/heimdall-uiapp#37]
@camelspeed commented on [Thu Jul 14 2016](https://github.com/Project-Heimdall/home/issues/22)

**Description**
Update the <html> markup for `Popular` view to match the approved wireframes.

**Acceptance Criteria**
- [x] When the user access the `Popular` view that the layout looks similar to the approved wireframe below:
![popular screen 1](https://cloud.githubusercontent.com/assets/1341786/16846132/4110844e-49b9-11e6-96f5-adf0a38dacbb.png)
- [x] Each card is displaying the following data:
    - [x] stars
    - [x] contributors
    - [x] watchers
    - [x] commits
    - [x] releases
    - [x] org name
    - [x] project name
    - [x] project description
    - [x] code language
    - [x] link to `README`
- [x] Dependant on https://github.com/Project-Heimdall/heimdall-webapp/issues/79 Data is accessible via a `GET` request:
    - [x] stars
    - [x] contributors
    - [x] watchers
    - [x] commits
    - [x] releases
    - [x] org name
    - [x] project name
    - [x] project description
    - [x] code language
    - [x] link to `README`

**Comment by herrjosua** [comment]
Waiting for the `GET` to be updated with `stars`,`watchers`, and `releases`. Once that is updated. I will be able to finish out this story.

**Comment by camelspeed** [comment]
@herrjosua I like the details here and the acceptance criteria.  Well done and something to build on.
