### ISSUE TITLE
Update the UI Style Guides

### ISSUE THREAD

**Issue by camelspeed** [Project-Heimdall/heimdall-uiapp#45]

**Comment by herrjosua** [comment]
`StyleDocco` does not work in the latest version of Chrome. It does work in Firefox. I will continue to research other options.

**Comment by herrjosua** [comment]
Worked with @onetrickwolf on researching why the `config.js` file had major changes. We were using an `beta` version of `Auerlia`, and `Auerlia Dialog` requires the `rc` version. Ran some local testing and saw no issues. Submitted a pull request for changes to be merged.

**Comment by herrjosua** [comment]
Finally got `kss` working on my local. Currently researching how to change the basic theme of KSS.
