### ISSUE TITLE
Design and style Modal View for text viewing

### ISSUE THREAD

**Issue by camelspeed** [Project-Heimdall/heimdall-uiapp#52]
Our first use will be to display a README in markdown.  The objective is to style the viewer that will be used.

**Comment by herrjosua** [comment]
@camelspeed How are we going to post the `readme` data in the modal? I have a modal popping up in my local branch, but I am unsure how to post the actual contents of the `readme` within the actual modal. @onetrickwolf @joelhanson

**Comment by herrjosua** [comment]
@camelspeed Worked with @onetrickwolf on researching why the `config.js` file had major changes. We were using an `beta` version of `Auerlia`, and `Auerlia Dialog` requires the `rc` version. Ran some local testing and saw no issues. Submitted a pull request for changes to be merged.

**Comment by camelspeed** [comment]
The modal viewer displays the README with a black background using white text which creates a hard to view contrast.  Also the modal viewers outline gets blurred with the main windows graying out.  We need to fix this for the demo today such that the modal view pops out like a modal dialog and the text is easy on the eyes against its background.

**Comment by camelspeed** [comment]
Closing this but the modal needs to be improved stylistically
