### ISSUE TITLE
Create HTML markup for Filters for Popular view

### ISSUE THREAD

**Issue by herrjosua** [Project-Heimdall/heimdall-uiapp#57]
**Description**
Update the static <html> markup for `Popular` view to include the filter sidebar, and sort by dropdown as shown below in the wireframe.

**Acceptance Criteria**
- [] When the user accesses the `Popular` view that they will see the filter sidebar.
- [] When the user accesses the `Popular` view that they will see the sort by dropdown.

![search result - option 8](https://cloud.githubusercontent.com/assets/1341786/16953883/bec698b0-4d9c-11e6-82eb-74b54437bb01.png)

**Comment by herrjosua** [comment]
@camelspeed Please review the issue `Description`, and `Acceptance Criteria` to ensure they meet our standards.

**Comment by onetrickwolf** [comment]
Had to jump on this to do some research and make a workaround to make the Bootstrap toggle buttons work but I think I found a fairly elegant solution.
