### ISSUE TITLE
Sort Top 20 Project  by Most Watchers

### ISSUE THREAD

**Issue by camelspeed** [Project-Heimdall/heimdall-uiapp#62]
@camelspeed commented on [Wed Jul 13 2016](https://github.com/Project-Heimdall/home/issues/16)

---

@camelspeed commented on [Tue Jul 19 2016](https://github.com/Project-Heimdall/home/issues/16#issuecomment-233654897)

Issue moved to [Project-Heimdall/heimdall-uiapp #61](https://github.com/Project-Heimdall/heimdall-uiapp/issues/61) via [**ZenHub**](https://www.zenhub.com/)

**Comment by onetrickwolf** [comment]
Duplicate to #61
