### ISSUE TITLE
User Research - first round

### ISSUE THREAD

**Issue by camelspeed** [Project-Heimdall/heimdall-uiapp#8]
@herrjosua commented on [Tue Jun 14 2016](https://github.com/Project-Heimdall/heimdall-webapp/issues/52)

Perform user interviews for STAGE using the following script as a base:

[User_Interview.docx](https://github.com/Project-Heimdall/heimdall-webapp/files/314690/User_Interview.docx)

**Comment by herrjosua** [comment]
- First interview with Keith has been completed. Will transcript notes into Confluences
- Second interview with Chan has been scheduled for 06/24 at 12
- Will schedule a third interview with Owen.

**Comment by herrjosua** [comment]
- Second interview has been rescheduled to Tuesday
- Third interview is tentatively scheduled for Thursday

**Comment by herrjosua** [comment]
Completed second interview.
