### ISSUE TITLE
Design how pagination will work

### ISSUE THREAD

**Issue by camelspeed** [Project-Heimdall/heimdall-uiapp#9]
@camelspeed commented on [Fri Jun 17 2016](https://github.com/Project-Heimdall/heimdall-webapp/issues/60)

This article has some simple pros/cons comparing Infinity Search to Pagination.
 https://uxplanet.org/ux-infinite-scrolling-vs-pagination-1030d29376f1#.vwssajfbb

We need a simple yet elegant, intuitive, and easy to use pagination design for the Search Results page.  It is unclear yet if we will use pagination for the Explore feature since Infinity may work better but we generally want to have a good pagination approach and design and then from their to see what components support it.

Things that pagination perhaps should do:

1.  User pages a chunk at a time (no need to say we want to page a variable amount).  Our chunk can be anywhere <= 25 depending on how big each row is and how much that means to scroll.
1. Should paging be only at the bottom like Google?
1. Show how many pages are there so a user can click on something in the middle (like Google).  User can go to the end if they desire like Google.
1. Paging should allow for Next Prev type like Google.

**Comment by herrjosua** [comment]
Found another interesting article on this. From reading the article a load more button might be an option as well.

https://www.smashingmagazine.com/2016/03/pagination-infinite-scrolling-load-more-buttons/
