### ISSUE TITLE
Update Project Details View with Contributors and Forks

### ISSUE THREAD

**Issue by camelspeed** [Project-Heimdall/heimdall-uiapp#90]
- [ ] Show Owners (GitHub Username, Link to GitHub Profile (new tab))
- [ ] Show # forks

**Comment by onetrickwolf** [comment]
@herrjosua forks is currently in the API call so you should be able to add it in with `${repo.forks}`

**Comment by herrjosua** [comment]
Added the `${repo.forks}` to the `project-details` view. The change has been submitted with the PR for #108
