### ISSUE TITLE
Update View Card style and markup so that it works in browser viewports > 1200px wide

### ISSUE THREAD

**Issue by herrjosua** [Project-Heimdall/heimdall-uiapp#91]
**Description**
Update the HTML markup and `LESS` styles for the cards to work in browser viewports above 1200 pixels in width. Currently the layout starts to break around the 1200 pixel wide viewport. Additionally once the view port drops below the 1200 pixel wide viewport it currently switches to a mobile first single column view.

**Acceptance Criteria**
- [] The layout of the cards is responsive between the viewport sizes of 1200 pixels to 1920 pixels wide.

**Additional Discussion**
For viewports under the 1200 pixel limit:
- do we want the filters to be:
     1. at the top of the page with a collapsible option
     2. at the bottom of the page
     3. an off canvas menu
-  Do we want the projects cards layout to be:
    1. Single column
    2. Double column

**Comment by camelspeed** [comment]
No longer needed.
